services:
  enset-banke-discovery-service:
    build: ./discovery-service
    container_name: enset-banke-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  enset-banke-config-service:
    build: ./config-service
    container_name: enset-banke-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-banke-discovery-service:8761/eureka
    depends_on:
      enset-banke-discovery-service:
        condition: service_healthy

  enset-customer-service:
    build: ./customer-service
    container_name: enset-customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-banke-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-banke-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-banke-config-service:
        condition: service_healthy

  enset-inventory-service:
    build: ./inventory-service
    container_name: enset-inventory-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-banke-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-banke-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      enset-banke-config-service:
        condition: service_healthy

  enset-billing-service:
    build: ./billing-service
    container_name: enset-billing-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-banke-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-banke-config-service:9999
    depends_on:
      enset-customer-service:
        condition: service_healthy
      enset-inventory-service:
        condition: service_healthy

  enset-gatewey-service:
    build: ./gatewey-service
    container_name: enset-gatewey-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-banke-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-banke-config-service:9999
    depends_on:
      enset-banke-config-service:
        condition: service_healthy
